//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane został zaktualizowane przez inną osobę. Należy odświeżyć stronę w celu wczytania nowych danych..
        /// </summary>
        internal static string FlashMessageConcurrencyWarning {
            get {
                return ResourceManager.GetString("FlashMessageConcurrencyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd związany z zapisem nowych danych..
        /// </summary>
        internal static string FlashMessageCreateError {
            get {
                return ResourceManager.GetString("FlashMessageCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zapisać nowych danych. Należy poprawić zaistniałe błędy..
        /// </summary>
        internal static string FlashMessageCreateInfo {
            get {
                return ResourceManager.GetString("FlashMessageCreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisanie nowych danych przebiegło pomyślnie..
        /// </summary>
        internal static string FlashMessageCreateSuccess {
            get {
                return ResourceManager.GetString("FlashMessageCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd związany z usuwaniem danych..
        /// </summary>
        internal static string FlashMessageDeleteError {
            get {
                return ResourceManager.GetString("FlashMessageDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięcie danych przebiegło pomyślnie..
        /// </summary>
        internal static string FlashMessageDeleteSucces {
            get {
                return ResourceManager.GetString("FlashMessageDeleteSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd związany z aktualizowaniem danych..
        /// </summary>
        internal static string FlashMessageEditError {
            get {
                return ResourceManager.GetString("FlashMessageEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zaktualizować danych. Należy poprawić zaistniałe błędy..
        /// </summary>
        internal static string FlashMessageEditInfo {
            get {
                return ResourceManager.GetString("FlashMessageEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizacja danych przebiegła pomyślnie..
        /// </summary>
        internal static string FlashMessageEditSuccess {
            get {
                return ResourceManager.GetString("FlashMessageEditSuccess", resourceCulture);
            }
        }
    }
}
